name: CI through Github Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Test
      run: |
        npm test -- --no-watch --no-progress --code-coverage --browsers=ChromeHeadlessCI
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage/ng-cocktails/lcov.info
        flags: unittests
        name: Unit tests
        fail_ci_if_error: true
        verbose: true
